### ISSUE TITLE
doesn't seem to produce usable output for modern NVME SSD, like Intel 600p series 256GB

### ISSUE THREAD

**Issue by ProBackup-nl** [bradfa/flashbench#9]
```
./flashbench -a /dev/nvme0n1 --blocksize 1024
align 68719476736 pre 47.5µs on 48µs post 47.5µs diff 487ns
align 34359738368 pre 47.4µs on 48µs post 47.5µs diff 551ns
align 17179869184 pre 47.4µs on 48µs post 47.5µs diff 509ns
align 8589934592 pre 47.5µs on 48µs post 47.6µs diff 502ns
align 4294967296 pre 47.5µs on 48µs post 47.6µs diff 441ns
align 2147483648 pre 57.3µs on 56.9µs post 55.5µs diff 457ns
align 1073741824 pre 55.5µs on 57.4µs post 56.3µs diff 1.52µs
align 536870912 pre 55.7µs on 57.4µs post 56.1µs diff 1.5µs
align 268435456 pre 47.5µs on 48µs post 47.5µs diff 491ns
align 134217728 pre 47.5µs on 48µs post 47.5µs diff 532ns
align 67108864 pre 47.5µs on 48µs post 47.6µs diff 483ns
align 33554432 pre 47.5µs on 48µs post 47.5µs diff 557ns
align 16777216 pre 47.5µs on 48µs post 47.5µs diff 504ns
align 8388608 pre 55.5µs on 57.4µs post 56µs diff 1.63µs
align 4194304 pre 55.5µs on 57.5µs post 56.1µs diff 1.68µs
align 2097152 pre 57.1µs on 58.5µs post 57.3µs diff 1.29µs
align 1048576 pre 47.6µs on 57.4µs post 57.4µs diff 4.95µs
align 524288 pre 47.5µs on 48µs post 47.4µs diff 501ns
align 262144 pre 47.5µs on 48µs post 47.4µs diff 572ns
align 131072 pre 47.5µs on 47.9µs post 47.4µs diff 461ns
align 65536 pre 47.5µs on 47.9µs post 47.5µs diff 477ns
align 32768 pre 47.5µs on 48µs post 47.5µs diff 535ns
align 16384 pre 47.7µs on 49µs post 47.6µs diff 1.36µs
align 8192 pre 55.8µs on 57.4µs post 56.3µs diff 1.33µs
align 4096 pre 55.8µs on 57.4µs post 56.3µs diff 1.34µs
align 2048 pre 55.8µs on 56.2µs post 56.2µs diff 218ns 
```
Intel product code: SSDPEKKW256G7X1
EAN: 5032037087766
UPC: 735858318259

**Comment by bradfa** [comment]
On 03/11 15:56, ProBackup-nl wrote:
> ```
> ./flashbench -a /dev/nvme0n1 --blocksize 1024
> align 68719476736 pre 47.5µs on 48µs post 47.5µs diff 487ns
> align 34359738368 pre 47.4µs on 48µs post 47.5µs diff 551ns
> align 17179869184 pre 47.4µs on 48µs post 47.5µs diff 509ns
> align 8589934592 pre 47.5µs on 48µs post 47.6µs diff 502ns
> align 4294967296 pre 47.5µs on 48µs post 47.6µs diff 441ns
> align 2147483648 pre 57.3µs on 56.9µs post 55.5µs diff 457ns
> align 1073741824 pre 55.5µs on 57.4µs post 56.3µs diff 1.52µs
> align 536870912 pre 55.7µs on 57.4µs post 56.1µs diff 1.5µs
> align 268435456 pre 47.5µs on 48µs post 47.5µs diff 491ns
> align 134217728 pre 47.5µs on 48µs post 47.5µs diff 532ns
> align 67108864 pre 47.5µs on 48µs post 47.6µs diff 483ns
> align 33554432 pre 47.5µs on 48µs post 47.5µs diff 557ns
> align 16777216 pre 47.5µs on 48µs post 47.5µs diff 504ns
> align 8388608 pre 55.5µs on 57.4µs post 56µs diff 1.63µs
> align 4194304 pre 55.5µs on 57.5µs post 56.1µs diff 1.68µs
> align 2097152 pre 57.1µs on 58.5µs post 57.3µs diff 1.29µs
> align 1048576 pre 47.6µs on 57.4µs post 57.4µs diff 4.95µs
> align 524288 pre 47.5µs on 48µs post 47.4µs diff 501ns
> align 262144 pre 47.5µs on 48µs post 47.4µs diff 572ns
> align 131072 pre 47.5µs on 47.9µs post 47.4µs diff 461ns
> align 65536 pre 47.5µs on 47.9µs post 47.5µs diff 477ns
> align 32768 pre 47.5µs on 48µs post 47.5µs diff 535ns
> align 16384 pre 47.7µs on 49µs post 47.6µs diff 1.36µs
> align 8192 pre 55.8µs on 57.4µs post 56.3µs diff 1.33µs
> align 4096 pre 55.8µs on 57.4µs post 56.3µs diff 1.34µs
> align 2048 pre 55.8µs on 56.2µs post 56.2µs diff 218ns 
> ```
> Intel product code: SSDPEKKW256G7X1
> EAN: 5032037087766
> UPC: 735858318259

Yeah, this is expected.  Modern SSD can have many MB, if not a few GB,
of SDRAM and/or other memory which isn't the final underlying flash in
order to provide for higher performance.  Additionally, the controllers
on higher performance/priced SSD drives can afford much greater
resources in order to provide high performance, which in the end masks
the underlying flash's physical properties quite well.

A cheap SD card for $4 can't do these kinds of things, so it's much
easier to use flashbench on cheap SD cards as they are unable to hide as
much of their underlying capabilities, compared to a modern SSD.

You can try upping the "--count" option to something like 1023 to give
flashbench a chance at giving you reasonable output, but I doubt it will
actually help.

For example, on an Intel 750 NVMe card, the output's still basically
useless:

```
$ sudo ./flashbench -a /dev/nvme0n1 --blocksize 1024 --count 1023
output is 0
align 68719476736	pre 11.8µs	on 13.6µs	post 12.9µs	diff 1.3µs
align 34359738368	pre 9.89µs	on 9.92µs	post 9.49µs	diff 230ns
align 17179869184	pre 14.7µs	on 14.7µs	post 14.5µs	diff 145ns
align 8589934592	pre 9.07µs	on 10.7µs	post 10.5µs	diff 913ns
align 4294967296	pre 14.2µs	on 27.1µs	post 27µs	diff 6.5µs
align 2147483648	pre 12.4µs	on 12.7µs	post 12.6µs	diff 185ns
align 1073741824	pre 14.3µs	on 13.8µs	post 13.9µs	diff -334ns
align 536870912	pre 14.4µs	on 15.4µs	post 14.2µs	diff 1.08µs
align 268435456	pre 13µs	on 13.2µs	post 13µs	diff 225ns
align 134217728	pre 13.4µs	on 14.1µs	post 14µs	diff 429ns
align 67108864	pre 14.1µs	on 16.8µs	post 15.3µs	diff 2.08µs
align 33554432	pre 11.8µs	on 12.3µs	post 11µs	diff 872ns
align 16777216	pre 12.3µs	on 13.5µs	post 12.1µs	diff 1.34µs
align 8388608	pre 12.6µs	on 12.4µs	post 12.2µs	diff -10ns
align 4194304	pre 11.7µs	on 12.2µs	post 11.7µs	diff 495ns
align 2097152	pre 10.5µs	on 11.8µs	post 11.3µs	diff 838ns
align 1048576	pre 10.9µs	on 11.4µs	post 11.2µs	diff 345ns
align 524288	pre 9.77µs	on 9.92µs	post 9.63µs	diff 220ns
align 262144	pre 10.7µs	on 11µs	post 10.3µs	diff 514ns
align 131072	pre 11.6µs	on 12.3µs	post 11.5µs	diff 763ns
align 65536	pre 12.4µs	on 13.4µs	post 12.6µs	diff 878ns
align 32768	pre 12.4µs	on 12.9µs	post 12.3µs	diff 579ns
align 16384	pre 12.4µs	on 12.7µs	post 12.4µs	diff 299ns
align 8192	pre 12µs	on 13.1µs	post 12.1µs	diff 1.03µs
align 4096	pre 14.4µs	on 15.1µs	post 12.1µs	diff 1.87µs
align 2048	pre 14µs	on 16.2µs	post 13.8µs	diff 2.36µs
```
